<a href="https://colab.research.google.com/github/boshetunmay1/paris-real-estate-analysis/blob/main/kursovaya.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ЗАГРУЗКА ДАННЫХ

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

file_path = '/content/drive/MyDrive/ParisHousing.csv'

df = pd.read_csv(file_path)
df = df.iloc[350:451]

plt.rcParams['figure.figsize'] = (12, 5)
sns.set_style("whitegrid")

# ПРЕДВАРИТЕЛЬНЫЙ АНАЛИЗ ДАННЫХ

## Характеристики выборки

In [7]:
print(f"Размер датасета: {df.shape[0]} строк × {df.shape[1]} столбцов")
display(df.head())
info_df = pd.DataFrame({
    'Тип данных':      df.dtypes,
    'Пропусков': df.isnull().sum(),
    'Пропусков %':   (df.isnull().sum() / len(df) * 100).round(2)
})
display(info_df)
display(df.describe().T.round(2))

Размер датасета: 101 строк × 17 столбцов

,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityCode,cityPartRange,numPrevOwners,made,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom,price
350,19649,11,0,1,83,87255,4,4,1999,1,0,595,6282,795,1,2,1970018.9
351,141,16,0,1,58,42248,5,4,1997,1,0,3411,8985,213,0,4,22670.7
352,22821,64,1,1,14,66304,9,8,1993,1,1,2060,103,491,1,2,2289134.3
353,533,76,1,1,55,94923,6,8,2021,1,1,654,3585,301,0,9,65465.1
354,67020,71,1,1,38,64361,4,7,2015,0,0,3647,997,640,0,1,6711051.5

                  Тип данных  Пропусков  Пропусков %
squareMeters           int64          0          0.0
numberOfRooms          int64          0          0.0
hasYard                int64          0          0.0
hasPool                int64          0          0.0
floors                 int64          0          0.0
cityCode               int64          0          0.0
cityPartRange          int64          0          0.0
numPrevOwners          int64          0          0.0
made                   int64          0          0.0
isNewBuilt             int64          0          0.0
hasStormProtector      int64          0          0.0
basement               int64          0          0.0
attic                  int64          0          0.0
garage                 int64          0          0.0
hasStorageRoom         int64          0          0.0
hasGuestRoom           int64          0          0.0
price                float64          0          0.0

,count,mean,std,min,25%,50%,75%,max
squareMeters,101.0,44216.89,29579.24,141.0,18926.0,38700.0,70763.0,99767.0
numberOfRooms,101.0,49.75,29.52,1.0,25.0,51.0,71.0,100.0
hasYard,101.0,0.52,0.50,0.0,0.0,1.0,1.0,1.0
hasPool,101.0,0.53,0.50,0.0,0.0,1.0,1.0,1.0
floors,101.0,53.58,29.58,1.0,32.0,54.0,80.0,99.0
cityCode,101.0,52864.53,29261.99,3.0,27552.0,50519.0,81044.0,99953.0
cityPartRange,101.0,5.98,2.91,1.0,4.0,7.0,8.0,10.0
numPrevOwners,101.0,6.22,2.43,1.0,4.0,7.0,8.0,10.0
made,101.0,2004.80,9.64,1990.0,1996.0,2004.0,2013.0,2021.0
isNewBuilt,101.0,0.49,0.50,0.0,0.0,0.0,1.0,1.0
hasStormProtector,101.0,0.45,0.50,0.0,0.0,0.0,1.0,1.0
basement,101.0,4618.27,2970.03,270.0,2060.0,3879.0,7245.0,9855.0
attic,101.0,4934.95,2756.64,42.0,2455.0,5066.0,6914.0,9730.0
garage,101.0,535.51,258.66,111.0,301.0,496.0,744.0,1000.0
hasStorageRoom,101.0,0.50,0.50,0.0,0.0,0.0,1.0,1.0
hasGuestRoom,101.0,4.74,3.09,0.0,2.0,5.0,7.0,10.0
price,101.0,4428739.44,2957864.41,22670.7,1908217.8,3880396.6,7082373.5,9985836.8

## Предварительаня обработка данных